<?php
defined( 'ABSPATH' ) or die( 'Access denied' );
return array(
	'all_languages'       => array(
		'bg_BG' => 'Български',
		'cs_CZ' => 'Čeština',
		'da_DK' => 'Dansk',
		'de_DE' => 'Deutsch',
		'el'    => 'Ελληνικά',
		'et_EE' => 'Eesti',
		'en_US' => 'English',
		'en_GB' => 'English (UK)',
		'es_ES' => 'Español',
		'fi'    => 'Suomi',
		'fr_FR' => 'Français',
		'hi_IN' => 'हिन्दी',
		'hr'    => 'Hrvatski',
		'id_ID' => 'Bahasa Indonesia',
		'it_IT' => 'Italiano',
		'ja'    => '日本語',
		'lv_LV' => 'Latviešu',
		'lt_LT' => 'Lietuvių',
		'hu_HU' => 'Magyar',
		'nb_NO' => 'Norsk bokmål',
		'nl_NL' => 'Nederlands',
		'pl_PL' => 'Polski',
		'pt_PT' => 'Português',
		'ro_RO' => 'Română',
		'ru_RU' => 'Русский',
		'sv_SE' => 'Svenska',
		'tr_TR' => 'Türkçe',
		'zh_CN' => '简体中文',
	),
	'level_colors'        => array(
		'default' => 'rgba(187, 187, 187, 0.5)',
		'low'     => '#79C9FF',
		'medium'  => '#FFBB79',
		'high'    => '#FF7979',
	),
	'feed_url'            => 'http://virusactivity.com/va-feed/',
	'widget_more_link'    => 'https://virusactivity.com/',
	'version_salt'        => 'f7de091531c4a593eb7c5150c6721fbd',
	'items_count_select'  => array( 0, 3, 5, 8, 10 ),
	'items_count_default' => 5,
);
